"""
This script contains the AutoFlow system, which consists of the following parts:
- Virtual landscape (defined & generated by Components.py)
- Vehicle agent object definitions
- Pathfinding algorithm
"""

from LandscapeComponents import *
from VehicleAgents import *

class MapState:

    """
    Virtual representation of the starting (current) state of the landscape and all vehicle agents within it.
    """

    def __init__(self, landscape: Landscape, vehicles: list[Vehicle]) -> None:
        self.landscape = landscape
        self.vehicles = vehicles